[build]
  command = "NETLIFY=true bun install && NETLIFY=true npx react-router build && cp build/server/index.js build/server/server.js"
  publish = "build/client"

[dev]
  command = "bun run dev"
  port = 4000
